## 00. PyTorch: Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


##  Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using `torch.Tensor()` -= https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Vector
Vector = torch.tensor([1, 2])
dimensions = Vector.ndim # number of dimensions basically the rank of the tensor
shape = Vector.shape # shape of the tensor basically the size of the tensor
print(dimensions)
print(shape)

1
torch.Size([2])


In [4]:
# Matrix

MATRIX = torch.tensor([[1, 2, 3], 
                       [4, 5, 6]])
MATRIX
print(MATRIX.ndim) # 2 dimensions
print(MATRIX.shape) # 2 rows and 3 columns

2
torch.Size([2, 3])


In [5]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], 
                   [4, 5, 6], 
                   [1, 2, 3]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [1, 2, 3]]])

In [6]:
TENSOR.ndim

3

In [7]:
TENSOR.shape # 2 matrix with 2 rows and 3 columns
#but if its like this

test = torch.tensor([[[1, 2, 3], 
                   [4, 5, 6]], 
                  [[1, 2, 3], 
                   [4, 5, 6]]])

test.shape # 2 matrices with 2 rows and 3 columns

torch.Size([2, 2, 3])

![dimensions](../images/ndime.png)

### Creating a range of tensors and tensors-like objects

In [8]:
# torch.arange(start, end, step) -> returns a 1D tensor with values from start to end with step size
torch.arange(0,10,2)
one_to_ten = torch.arange(1,10)

In [9]:
# creating tensors-like objects
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes are important for GPU accelerations. It is one of the 3 big errors we'll run into with PyTorch & deep learning:
1. Tensor not right dataype
2. Tensors are not the right shape
3. Tensors not on the right device (CPU vs GPU)

In [10]:
# we all know that the default data type of a tensor is float32
# we can change it by using dtype
ten_zeros = torch.zeros_like(input=one_to_ten, 
                             dtype=torch.float64,# this function is used to change the data type of the tensor
                             #32 bit floating point number is a single precision number while 64 bit floating point number is a double precision number
                             device='cuda', # this function is used to change the device of  the tensor which are: cpu, cuda, mkldnn, opengl, opencl, ideep, hip, msnpu
                             requires_grad=False# wether or not to track the gradients with this tensors operations
                             )
ten_zeros.dtype

torch.float64

### Manipulating a Tensor (tensor operations)

Tensor operations inclide:
- Addition
- Subtraction
- Multiplication 
- Division

all of which are element-wise operations
- Matrix Multiplication


In [13]:
#addition 
x = torch.tensor([10, 20, 30])

print(x + 10)

#multiplication
print(x * 10)


#division
print(x / 10)


#subtraction
print(x - 10)



tensor([20, 30, 40])
tensor([100, 200, 300])
tensor([1., 2., 3.])
tensor([ 0, 10, 20])


### Matrix Multiplication

Dot product of two matrices is the sum of the products of the corresponding entries of the two sequences of numbers.

and all rules of matrix multiplication apply

1. inner dimensions must match
2. resulting matrix has the shape of the outer dimensions

In [16]:
#use matrix multiplication to multiply [1,2,3
#                                     [4,5,6]
# and [7,8]
#     [9,10]
# and [11,12]

tensor1 = torch.tensor([[1,2,3],
                        [4,5,6]])
tensor2 = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])
print(tensor1.shape)
print(tensor2.shape)
torch.matmul(tensor1, tensor2)


torch.Size([2, 3])
torch.Size([3, 2])


tensor([[ 58,  64],
        [139, 154]])

To fix some of the issues with matrix multiplication, we can use the `torch.transpose()` function to **transpose** the dimensions of a tensor.

so if we have a tensor `x` with shape `(2, 3)` and another tensor `y` shaped `(2,3)` also we can use the `torch.transpose()` function to swap the dimensions of `y` to `(3, 2)` and then we can multiply the two tensors together.

### Finding the min, max, mean, sum, and standard deviation of a tensor (tensor aggregations)